version: "3"
services:
  node-boilerplate:
    build: .
    command: npm run start
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/node-es8-boilerplate
      - PORT=8000
      - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
      - JWT_EXPIRATION_MINUTES=15
      - RATE_LIMIT_TIME=15
      - RATE_LIMIT_REQUEST=15
      - REDIS_HOST=redisdb
      - REDIS_PORT=6379
    volumes:
      - .:/app
    ports:
      - "80:8000"
    links:
      - mongodb
      - redisdb
    depends_on:
      - mongodb
      - redisdb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  
  redisdb:
    image: redis
    ports:
      - "6379:6379"